# stdlib
from typing import Any

# this package
from natsort.utils import regex_chooser as regex_chooser  # noqa: F401

def main(*arguments: Any) -> None: ...
def range_check(low: Any, high: Any): ...
def check_filters(filters: Any): ...
def keep_entry_range(entry: Any, lows: Any, highs: Any, converter: Any, regex: Any): ...
def keep_entry_value(entry: Any, values: Any, converter: Any, regex: Any): ...
def sort_and_print_entries(entries: Any, args: Any) -> None: ...
