# stdlib
import enum
from typing import Any, Dict, List, Tuple

enum_options: List[str]
enum_do_nothing: List[str]
enum_combos: List[Tuple[str, Tuple[str, str]]]
enum_aliases: List[Tuple[str, str]]
enum_fields: Dict[str, int]
combined_value: Any

class ns(enum.IntEnum):
	FLOAT: int = ...
	SIGNED: int = ...
	NOEXP: int = ...
	PATH: int = ...
	LOCALEALPHA: int = ...
	LOCALENUM: int = ...
	IGNORECASE: int = ...
	LOWERCASEFIRST: int = ...
	GROUPLETTERS: int = ...
	UNGROUPLETTERS: int = ...
	NANLAST: int = ...
	COMPATIBILITYNORMALIZE: int = ...
	NUMAFTER: int = ...
	DEFAULT: int = ...
	INT: int = ...
	UNSIGNED: int = ...
	REAL: int = ...
	LOCALE: int = ...

NS_DUMB: int
